---
- name: "upgrade packages"
  become: true
  yum:
    name: "*"
    state: latest

- name: "install node dependencies"
  become: true
  yum:
    name: ["nodejs", "npm"]
    state: present
    update_cache: true

- name: "Create directory for web"
  file:
    path: /home/ubuntu/web
    state: directory


- name: "copy artifact"
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/web/artifact.tar.gz

- name: "Extract artifact files"
  become: true
  shell: |
    cd /home/ubuntu/web
    tar -xvf artifact.tar.gz    

- name: "start"
  shell: npm install
         npm audit fix --audit-level=critical --force 
         pm2 stop default
         pm2 start npm -- start
